### ISSUE TITLE
ckeditor.js 404 when creating blocks

### ISSUE THREAD

**Issue by davet1985** [networking/init-cms-bundle#13]
When loading the admin pages ckeditor.js is loaded fine ,from /bundles/ivoryckeditor/ckeditor.js. However, when navigating to a page and trying to add a new block, when clicking the create button it attempts to get ckeditor.js from /admin/cms/pages/3/bundles/ivoryckeditor/ckeditor.js. This path is not correct and the file does not exist.

Do you know what is happening here?

Cheers,
Dave

**Comment by ychadwick** [comment]
We override the base.js from sonata now with our own file.
