### ISSUE TITLE
new Symfony version compatibility

### ISSUE THREAD

**Issue by Warxcell** [networking/init-cms-bundle#14]
networking/init-cms-bundle dev-master requires symfony/symfony >=2.3,< 2.4-dev -> no matching package found.

**Comment by grzegorzmurdzek** [comment]
I'm using Symfony 2.6 in my projects and I found that init-cms-bundle is incompatible with it (symfony/symfony >=2.3,<2.6-dev depencency). Are there any work-in-progress version ready for an update to the latest Symfony 2 versions?

**Comment by ychadwick** [comment]
Hi there grzegorzmurdzek. We are not planning on making and update for the 2.6 Version of Symfony just yet as there is always the problem of making sure all the dependencies that we use are also compatible with 2.6. But please create a fork of the project :)

The next upgrade will probably to version 3.0, but that is a way off.
