### ISSUE TITLE
Warning: array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by mvar** [networking/init-cms-bundle#25]
After I tried to remove page block on demo site, I got this error:

```
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/vhosts/initcms.com/private/demo_cms/vendor/networking/init-cms-bundle/Networking/InitCmsBundle/Twig/Extension/NetworkingHelperExtension.php on line 543 
```

![image](https://cloud.githubusercontent.com/assets/1286752/4221154/11093c9c-3907-11e4-9789-61a5bcb516a3.png)

**Comment by ychadwick** [comment]
We will be updating the demo site soon. A lot has been changed
