### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by jimmy626ooip** [networking/init-cms-bundle#26]
Hi,

I am trying to install the initcms bundle but i get some errors when i do the composer require:

Package sonata-project/jquery-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.

Also the mopa bootstrapbundle and the knp paginator bundle has a require on dev-master, can this be set on a version? It will boost the composer update performance a lot.

**Comment by ychadwick** [comment]
The problem with the markdown bundle is that the sonata-project/formatter-bundle requires it, and we need the formatter bundle as it helps with the building of ckeditor, specifically the image and file browsers. This will only change when we can upgrade to a more stable version of the formatter bundle.

As for Mopa, they do not yet have stable version, the most stable is 3.0.0-beta4. 
The best thing for you to do is add "prefer-stable":true to your composer.json file.
