### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by a-salihov** [networking/init-cms-bundle#29]
I get an error during composer update operation:

PHP Fatal error:  Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /home/salikhov/projects/campgite/vendor/sonata-project/admin-bundle/Block/AdminListBlockService.php on line 32

It seems that the current set of dependencies for Sonata modules not working:

"sonata-project/doctrine-orm-admin-bundle": ">=2.2.4,<2.3-dev",
 "sonata-project/intl-bundle": ">=2.1,<2.3-dev",
 "sonata-project/notification-bundle": ">=2.2,<2.3-dev",
 "sonata-project/admin-bundle": ">=2.2,<2.3-dev",
"sonata-project/media-bundle": ">=2.2.5,<2.3-dev",
 "sonata-project/user-bundle": ">=2.2.0,<2.3-dev",
 "sonata-project/formatter-bundle": ">=2.3.0",

**Comment by ychadwick** [comment]
You will need to report this to the sonata-project people, we depend on the sonata-project/admin-bundle v2.2, this bundle includes the dependency for the sonata-project/block-bundle, v2.2 > 2.7.
It looks like you are getting the block-bundle 2.3 which is not compatible with the admin-bundle 2.2. 
I have never had this problem so far, but I would suggest you add to your composer.json file the requirement for "sonata-project/block-bundle": ">=2.2,<2.3-dev"
I will test this in our bundle to see if this helps

**Comment by a-salihov** [comment]
I created issue in SonataAdminBundle
https://github.com/sonata-project/SonataAdminBundle/issues/2826

and get such answer:
https://gist.github.com/rande/9c0cfbd751d3e64b893f

But how can I override current InitCmsBundle dependencies? If I just put after "networking/init-cms-bundle": "dev-master", recommended versions:

    "sonata-project/intl-bundle": "~2.2@dev",
    "sonata-project/admin-bundle": "~2.4@dev",
    "sonata-project/doctrine-orm-admin-bundle": "~2.4@dev",
    "sonata-project/notification-bundle": "~2.2@dev",
    "sonata-project/block-bundle": "~2.3@dev",
    "sonata-project/media-bundle": "~2.4@dev",
    "sonata-project/user-bundle": "~2.2@dev",
    "sonata-project/formatter-bundle": "~2.4@dev",

 then composer write "Your requirements could not be resolved to an installable set of packages"

**Comment by a-salihov** [comment]
I also tried to override two suspicious bundle versions

    "sonata-project/block-bundle": "2.2.9",
    "sonata-project/formatter-bundle": "2.3.3",

After that I get error in the InitCmsBundle:

PHP Fatal error:  Access to undeclared static property: phpFastCache::$default_chmod in /.../vendor/networking/init-cms-bundle/Networking/InitCmsBundle/Lib/PhpCache.php on line 62

**Comment by ychadwick** [comment]
There are various problems with the sonata project bundle, the admin-bundle and the user-bundle need different version of the block bundle.
This is what can make you crazy with dependencies.
Thanks for the tipp about the PhpCache class, they changed there class variables, yay.

**Comment by rande** [comment]
I think the dependencies should be fixed now.

**Comment by ychadwick** [comment]
I have changed the depencies for the bundle. Not moving to sonatas 2.4 just yet.
also the issue with the phpcache should be resolved.
