### ISSUE TITLE
database update

### ISSUE THREAD

**Issue by a-salihov** [networking/init-cms-bundle#30]
I have my test project on the dev-master version, which has been download in December. 
Now I perform a composer update. (Actually version has been changed from 2.5.2+ to 2.5.6)

How can I know if were made changes to the database structure to update it too?

**Comment by ychadwick** [comment]
As far as I know there were little or no changes made to the DB structure. Quickly run
````shell
app/console doctrine:schema:update --dump-sql
````
On the command line to see what changes are to be made
