### ISSUE TITLE
BC break in PageHelper

### ISSUE THREAD

**Issue by zeliard91** [networking/init-cms-bundle#41]
Hello,

Since the refactorisation made in 698e6ec9208cf7f921a705e1511c4a1ce8d9a52f there is a bug in https://github.com/networking/init-cms-bundle/blob/master/Helper/PageHelper.php#L213

```php
$contentRouteClass = $contentRouteManager->getClass();
```

The getClass() method does not exist anymore.

**Comment by ychadwick** [comment]
Hi there, I have returned the method for retrieving the class that is used for the content based routes. See commit 8381aad
Thank you once again for your help

**Comment by ychadwick** [comment]
Sorry, check out commit 30912d4

**Comment by zeliard91** [comment]
Great ! Thank you for your quick actions :)
