### ISSUE TITLE
FYI: parallel work on upgrades

### ISSUE THREAD

**Issue by lennardk** [networking/init-cms-bundle#46]
Hi Yorkie,

Just as an FYI, at Batavierenrace we've been making some on and off efforts making your bundle compatible with your existing internal symfony 2.8 project. We've made quite some progress and were actually close to issuing pull requests when we noticed you had started similar work yourself.
As symfony 2.8 will probably remain a requirement for us for a while, we're interesting in seeing if this is something you would be willing to keep this project compatible with for now.
Our current work can be seen at https://github.com/batavierenrace/init-cms-bundle/tree/upgrade_sonata_3_0, feel free to use any patches/refactors/etc found in there.

Lennard and Jorne at Stichting Batavierenrace

**Comment by ychadwick** [comment]
Hi there,

Thanks for your work, we have currently moved on to symfony 3.4 and will probably only be making hot fixes to the 2.8 version of our cms.

Our work was more inline with upgrading to the new symfony version, which meant also upgrading sonata.
